### ISSUE TITLE
Not able to add your plug in. 

### ISSUE THREAD

**Issue by hisgarden** [tscole/gridsome-source-googlesheet#1]
Hi Tim, I try to follow the instruction on https://gridsome.org/plugins/gridsome-source-googlesheet and do the yarn add gridsome-source-googlesheets, I got this: An unexpected error occurred: "https://registry.yarnpkg.com/gridsome-source-googlesheets: Not found".

**Comment by tscole** [comment]
Sorry, there is a typo in the readme. I will correct it. The command you need is
`yarn add gridsome-source-googlesheet`
